fastlane_version "2.24.0"

default_platform :ios

platform :ios do

   lane :example do
      puts("this is my first 🚀 lane")
   end

   lane :build do
     puts("lets try to build something here...")
     provisioning
     build_app
     puts("it works! 🙈")
   end

   lane :provisioning do
     puts("let me handle the provisioning for you...")
     match(type: "development")
     match(type: "appstore")
     puts("provisioning sorted! 😋")
   end

    lane :metrics do
      scan(scheme: "JenkinsFastlaneExampleTests", code_coverage: true, derived_data_path: "./DerivedData", output_directory: "./reports")
      # slather(cobertura_xml: true, jenkins: true, scheme: "JenkinsFastlaneExampleTests", build_directory: "./DerivedData", output_directory: "./reports", proj: "./JenkinsFastlaneExample.xcodeproj")
      sh("cd .. && lizard -l swift --xml > ./reports/lizard-report.xml")
      swiftlint(executable: "Pods/SwiftLint/swiftlint", output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
      sonar
    end

end
