fastlane_version "2.24.0"

default_platform :ios

platform :ios do

   lane :example do
      puts("this is my first 🚀 lane")
   end

   lane :build do
     puts("lets try to build something here...")
     match(type: "development")
     build_app
     puts("it works! 🙈")
   end

   lane :provisioning do
     puts("let me handle the provisioning for you...")
     match(type: "development")
     match(type: "appstore")
     puts("provisioning sorted! 😋")
   end

end
